package Acme::CPANLists::Import::PerlAdvent::2016_12_09;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2016/2016-12-09.html] (retrieved on 2016-12-29). Visit the URL for the full contents.",entries=>[{module=>"Data::Domain"},{module=>"Data::Domain::Dependencies"},{module=>"Params::Validate"},{module=>"Params::Validate::Dependencies"}],summary=>"Modules mentioned in Perl Advent Calendar 2016 (day 09)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2016 (day 09)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2016/2016-12-09.html> (retrieved on 2016-12-29). Visit the URL for the full contents.

