package Acme::CPANLists::Import::PerlAdvent::2016_12_16;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2016/2016-12-16.html] (retrieved on 2016-12-29). Visit the URL for the full contents.",entries=>[{module=>"Geo::Coder::OpenCage"},{module=>"Geo::Parser::Text"},{module=>"Text::NLP"}],summary=>"Modules mentioned in Perl Advent Calendar 2016 (day 16)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2016 (day 16)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2016/2016-12-16.html> (retrieved on 2016-12-29). Visit the URL for the full contents.

