package Acme::CPANLists::Import::PerlAdvent::2016_12_06;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2016/2016-12-06.html] (retrieved on 2016-12-29). Visit the URL for the full contents.",entries=>[{module=>"BPM::Engine"},{module=>"Schedule::LongSteps"}],summary=>"Modules mentioned in Perl Advent Calendar 2016 (day 06)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2016 (day 06)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2016/2016-12-06.html> (retrieved on 2016-12-29). Visit the URL for the full contents.

