package Acme::CPANLists::Import::PerlAdvent::2016_12_24;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2016/2016-12-24.html] (retrieved on 2016-12-29). Visit the URL for the full contents.",entries=>[{module=>"Data::Validate::Domain"},{module=>"Test2::Bundle::Extended"},{module=>"Test2::Bundle::More"},{module=>"Test2::Compare::Base"},{module=>"Test2::Suite"},{module=>"Test::Deep"},{module=>"Test::More"}],summary=>"Modules mentioned in Perl Advent Calendar 2016 (day 24)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2016 (day 24)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2016/2016-12-24.html> (retrieved on 2016-12-29). Visit the URL for the full contents.

