package Acme::CPANLists::Import::PerlAdvent::2016_12_17;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2016/2016-12-17.html] (retrieved on 2016-12-29). Visit the URL for the full contents.",entries=>[{module=>"API::CLI"},{module=>"App::AppSpec"},{module=>"App::Cmd"},{module=>"App::Spec"},{module=>"Applify"},{module=>"CLI::Dispatch"},{module=>"CLI::Framework"},{module=>"Getopt::Long"},{module=>"Getopt::Long::Descriptive"},{module=>"Getopt::Long::DescriptivePod"},{module=>"MooX::Cmd"},{module=>"MooseX::App"},{module=>"MooseX::App::Cmd"},{module=>"MooseX::Getopt"},{module=>"MouseX::App::Cmd"},{module=>"Params::Validate"},{module=>"Pod::Usage"},{module=>"Term::ShellUI"}],summary=>"Modules mentioned in Perl Advent Calendar 2016 (day 17)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2016 (day 17)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2016/2016-12-17.html> (retrieved on 2016-12-29). Visit the URL for the full contents.

