package Acme::CPANLists::Import::PerlAdvent::2016_12_03;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2016/2016-12-03.html] (retrieved on 2016-12-29). Visit the URL for the full contents.",entries=>[{module=>"Bencher"},{module=>"Bencher::Scenario::LevenshteinModules"},{module=>"Bencher::Tiny"},{module=>"Benchmark"},{module=>"Dist::Zilla"},{module=>"Dumbbench"},{module=>"Text::Levenshtein"},{module=>"Text::Levenshtein::Flexible"},{module=>"Text::Levenshtein::XS"},{module=>"Text::LevenshteinXS"}],summary=>"Modules mentioned in Perl Advent Calendar 2016 (day 03)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2016 (day 03)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2016/2016-12-03.html> (retrieved on 2016-12-29). Visit the URL for the full contents.

