package Acme::CPANLists::Import::PerlAdvent::2016_12_20;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2016/2016-12-20.html] (retrieved on 2016-12-29). Visit the URL for the full contents.",entries=>[{module=>"PDF::Reuse"}],summary=>"Modules mentioned in Perl Advent Calendar 2016 (day 20)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2016 (day 20)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2016/2016-12-20.html> (retrieved on 2016-12-29). Visit the URL for the full contents.

