package Acme::CPANLists::Import::PerlAdvent::2016_12_08;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2016/2016-12-08.html] (retrieved on 2016-12-29). Visit the URL for the full contents.",entries=>[{module=>"Geo::Coder::OpenCage"}],summary=>"Modules mentioned in Perl Advent Calendar 2016 (day 08)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2016 (day 08)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2016/2016-12-08.html> (retrieved on 2016-12-29). Visit the URL for the full contents.

