#!/usr/bin/env perl

use 5.010;
use strict;
use warnings;
use FindBin '$Bin';

use App::CreateAcmeCPANListsImportModules;
use Perinci::Sub::Util qw(gen_curried_sub);
use Perinci::CmdLine::Any;

my %add_modules = (
    "01" => ["Meta::Grapher::Moose"], # not linked
    "08" => ["Geo::Coder::OpenCage"], # not linked
    "10" => ["Text::CSV_XS"], # not linked
    "18" => ["Text::Fuzzy"], # not linked
);

gen_curried_sub(
    'App::CreateAcmeCPANListsImportModules::create_acme_cpanlists_import_modules',
    {
        modules => [
            {
                name => '2016',
                url => "http://perladvent.org/2016/",
                extract_urls => [map {"http://perladvent.org/2016/2016-12-$_.html"} "01".."25"],
                summary => 'Modules mentioned in Perl Advent Calendar 2016',
                add_modules => [map {@$_} values %add_modules],
            },
            (map {
                +{
                    name => "2016_12_$_",
                    url => "http://perladvent.org/2016/2016-12-$_.html",
                    summary => "Modules mentioned in Perl Advent Calendar 2016 (day $_)",
                    add_modules => [@{ $add_modules{$_} // [] }],
                },
            } "01".."24"),
        ],
        namespace => 'Acme::CPANLists::Import::PerlAdvent',
        user_agent => 'Mozilla/5.0',
        dist_dir => "$Bin/..",
    },
    'app',
);

Perinci::CmdLine::Any->new(
    url => '/main/app',
    log => 1,
)->run;
